# Location on Server: /etc/nginx/sites-available/unish-lab
# Domain used for demonstration: lab.unishdhungana.com.np

server {
    server_name your-domain.com;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Standard directory with index.html
    location /abc/ {
        try_files $uri $uri/ =404;
    }

    # Custom file routing for xyz
    location /xyz/ {
        # This tells Nginx to look for xyz.html directly when the /xyz/ folder is hit
        try_files $uri /xyz/xyz.html =404;
    }

    # Custom location for routing /pqr
    location /pqr/ {
        try_files $uri /pqr/random_text.html =404;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/your-domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/your-domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    # HSTS (6 months)
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
    # Prevent MIME-sniffing
    add_header X-Content-Type-Options nosniff;
    # Prevent Clickjacking
    add_header X-Frame-Options DENY;
}

server {
    if ($host = your-domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name your-domain.com;
    return 404; # managed by Certbot


}