# Location on Server: /etc/nginx/sites-available/unish-lab
# Domain used for demonstration: lab.unishdhungana.com.np

server {
    listen 80;
    server_name lab.unishdhungana.com.np;

    root /var/www/html;
    index index.html;

    # Root handler
    location / {
        try_files $uri $uri/ =404;
    }

    # Directory-based routing
    location /abc/ {
        try_files $uri $uri/ =404;
    }

    # Explicit file mapping
    location /xyz/ {
        try_files /xyz.html =404;
    }

    location /pqr/ {
        try_files /random_text.html =404;
    }
}